packages:
  brews:
    - "git"
    - "bat"
    - "bottom"
    - "btop"
    - "fd"
    - "curline"
    - "fd"
    - "ffmpeg"
    - "fish"
    - "fzf"
    - "gh"
    - "git-delta"
    - "go"
    - "eza"
    - "lazygit"
    - "lv"
    - "mise"
    - "neovim"
    - "oh-my-posh"
    - "ripgrep"
    - "zoxide"
