name: "CI: GitHub Actions lint"

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/**"
      - ".github/actions/**"
  pull_request:
    paths:
      - ".github/workflows/**"
      - ".github/actions/**"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# デフォルト権限を空にし、jobごとに付与する
permissions: {}

jobs:
  actionlint:
    runs-on: ubuntu-slim
    timeout-minutes: 10
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Run actionlint
        uses: raven-actions/actionlint@3d39aea434753780c3b3d4a1a31c854b4dbf49d7 # v2.2.0

  ghalint:
    runs-on: ubuntu-slim
    timeout-minutes: 10
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Setup Nix
        uses: ./.github/actions/setup-nix
        with:
          skipPush: "true"

      - name: Check workflows
        run: nix shell nixpkgs#ghalint -c ghalint run

      - name: Check composite actions
        run: nix shell nixpkgs#ghalint -c ghalint run-action

  zizmor:
    runs-on: ubuntu-slim
    timeout-minutes: 10
    permissions:
      contents: read
      actions: read

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Run Zizmor
        uses: zizmorcore/zizmor-action@5f14fd08f7cf1cb1609c1e344975f152c7ee938d # v0.5.6
        with:
          online-audits: "false"
          version: "1.29.0"
          advanced-security: false
