name: 'CI: Nix Build'

on:
  push:
    branches:
      - main
    paths:
      - "**/*.nix"
      - "flake.lock"
      - ".github/workflows/nix-build.yaml"
      - ".github/actions/setup-nix/action.yaml"
  pull_request:
    paths:
      - "**/*.nix"
      - "flake.lock"
      - ".github/workflows/nix-build.yaml"
      - ".github/actions/setup-nix/action.yaml"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build-macos:
    runs-on: macos-26
    timeout-minutes: 45
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Setup Nix
        uses: ./.github/actions/setup-nix
        with:
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
          skipPush: ${{ github.event_name == 'pull_request' }}

      - name: Build Darwin checks
        run: |
          nix build --show-trace --keep-going --no-link \
            .#checks.aarch64-darwin.formatting \
            .#checks.aarch64-darwin.statix \
            .#checks.aarch64-darwin.deadnix

      - name: Build darwinConfigurations
        run: nix build --show-trace --no-link .#darwinConfigurations.suzuMac.system

      - name: Print disk usage
        run: df -h

  build-wsl:
    runs-on: ubuntu-24.04
    timeout-minutes: 45
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Setup Nix
        uses: ./.github/actions/setup-nix
        with:
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
          skipPush: ${{ github.event_name == 'pull_request' }}

      - name: Build nixosConfigurations
        run: nix build --show-trace --no-link .#nixosConfigurations.suzuWsl.config.system.build.toplevel

      - name: Print disk usage
        run: df -h
