name: 'CI: Neovim plugins'

on:
  push:
    branches:
      - main
    paths:
      - "nvim/**"
      - "flake.lock"
      - "flake.nix"
      - ".github/workflows/nix-nvim.yaml"
      - ".github/actions/setup-nix/action.yaml"
  pull_request:
  workflow_dispatch:

jobs:
  check-nvim:
    runs-on: macos-26
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Nix
        uses: ./.github/actions/setup-nix
        with:
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
          skipPush: ${{ github.event_name == 'pull_request' }}

      - name: Link Neovim config
        run: |
          mkdir -p ~/.config
          ln -s "$PWD/nvim" ~/.config/nvim

      - name: Restore Neovim plugins
        run: |
          nix shell nixpkgs#neovim nixpkgs#git -c ./scripts/nvim-restore.sh ~/.config/nvim

      - name: Check Neovim configuration
        run: |
          nix shell nixpkgs#neovim nixpkgs#git -c nvim --headless "+qa"
